In [2]:
import numpy as np
import scipy as sp
import matplotlib as mpl


In [6]:
#importer la fonction compteur() du module projet1
from projet1 import compteur3 
compteur3()

0
1
2


In [11]:
#importer toutes les fonctions d'un module
from projet1 import *
compteur3() #fonction 1
print("--------")
table(2,5) #fonction 2

0
1
2
--------
1 * 2 = 2
2 * 2 = 4
3 * 2 = 6
4 * 2 = 8
5 * 2 = 10


In [17]:
#importer tkinter utile pour créer des interfaces graphiques
from tkinter import *

window = Tk() #Créer une première fenêtre
window.mainloop() #Afficher la fenêtre


In [36]:
import numpy as np #importer numpy
#créer un tableau à l'aide du constructeur array
Noms=np.array(["Ouahbi Hatim","Yassine Zaiouane","Zakaria ez-zahar","Souaad Balhouss"])
print(Noms)#afficher le tableau
print("dimension=",tableau.ndim) #afficher la dimension du tableau
print("forme=",tableau.shape) #afficher la forme du tableau


['Ouahbi Hatim' 'Yassine Zaiouane' 'Zakaria ez-zahar' 'Souaad Balhouss']
dimension= 1
forme= (5,)


In [39]:
#tableau rempli de 0 à 2 lignes et 3 colonnes
tableau=np.zeros((2,3))
type(tableau.shape)

tuple

In [43]:
#tableau rempli de 0 à 2 lignes et 3 colonnes
tableau=np.ones((2,3))
print(tableau)
print("size of the array is:",tableau.size) #lignes*colonnes

[[1. 1. 1.]
 [1. 1. 1.]]
size of the array is: 6


In [47]:
Aleatoire = np.random.randint(0, 10, [2, 3]) # tableau d'entiers aléatoires de 0 a 10 et de dimension 2x3
Aleatoire

array([[2, 7, 7],
       [3, 3, 6]])

In [51]:
tableau1=np.arange(0,10,0.5) #parcourir [0,10] par pas de 0.5
tableau1

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])